### ISSUE TITLE
FR: option to remove underline from to doc links

### ISSUE THREAD

**Issue by laurentpayot** [elm-land/vscode#5]
Links to docs are great but, for me at least, underlines catch my eyes too much and make code difficult to read. It looks too much like an exception.
Could you please add an option so links to docs not underlined?

Cheers,
Laurent

**Comment by lydell** [comment]
TIL you can configure to only underline in imports:

<img width="979" alt="image" src="https://github.com/elm-land/vscode/assets/2142817/5f17a23b-3300-4d0b-83a3-399bb6be36ec">

Then you can click `import Time` but `Time.millisToPosix` won’t be clickable.

Ideally I might still want `Time.millisToPosix` to be clickable (but not highlighted) (or even be able to see the source code for `millisToPosix`, which is sometimes useful for power users).

**Comment by laurentpayot** [comment]
Oh that’s just great. Thanks @lydell :+1:
